### ISSUE TITLE
Enrich the dataset with International Classification of Diseases

### ISSUE THREAD

**Issue by iradche** [IPMITMO/medical-data#5]

**Comment by tatarsky-v** [comment]
http://ec.europa.eu/eurostat/ramon/nomenclatures/index.cfm?TargetUrl=LST_CLS_DLD_NOHDR&StrNom=CL_ICD9-CM&StrLanguageCode=EN

**Comment by tatarsky-v** [comment]
http://www.nber.org/data/icd-hcc-crosswalk-icd-rxhcc-crosswalk.html
